.\" exas.1, v 1.0 2023/10/20
.Dd 2023-10-20
.Dt exas 1
.Os Linux
.Sh NAME
.Nm exas
.Nd execute commands as another user
.Sh SYNOPSIS
.Nm
.Op Fl u Ar user
.Op Fl -
.Ar command
.Op Ar args
.Sh DESCRIPTION
The
.Nm
utility executes the given as another user. The
.Ar command
argument is always mandatory.
.Pp
The options are as follows:
.Bl -tag -width tenletters
.It Fl u Ar user
Execute the command as
.Ar user .
The default is root.
Note: On some systems multiple usernames can resolve to one UID. Like root and
toor on FreeBSD, resolve to UID 0.
.El
.Sh EXIT STATUS
.Pp
The
.Nm
utility exits 0 on success, and >0 if an error occurs.
.Sh SEE ALSO
.Xr doas 1 ,
.Xr sudo 8